// insert token after login here

// ========== token
// admin
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmFmYWUyMTFhMDViOTQ5YjcwZjU3YzEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MDUzNDk5MDksImV4cCI6MTYwODk0OTkwOX0.01reBa3UddfV5XqcHcx-hW-2KV4kMi6t6d9jaT1ZfWE
// user
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmFmYjkzZDNjMjA4NDYxZjBlMmRiNWUiLCJyb2xlIjoidXNlciIsImlhdCI6MTYwNTM1MjE1NywiZXhwIjoxNjA4OTUyMTU3fQ.EaBTsBmhOaNDX90o2TedeHpi-jg1S2jlsCFfzpMT6R4
@ctype = application/json

// please change post id
@post1= 5fb116a54353ae36539bb9b3
@post2= 5fafb6f137abec5fc02f8ab4

###
http://localhost:3000

###

POST http://localhost:3000/api/login
Content-Type: {{ctype}}

{
    "username": "rod41733",
    "password": "12345678"
}

###
POST http://localhost:3000/api/dev/register
Content-Type: {{ctype}}

{
    "username": "rod41733",
    "password": "12345678",
    "displayName": "Rodchananat",
    "role": "user"
}

###
GET http://localhost:3000/api/user/5fafae211a05b949b70f57c1
Content-Type: {{ctype}}
Authorization: Bearer {{token}}



###
GET http://localhost:3000/api/post
Content-Type: {{ctype}}
Authorization: Bearer {{token}}


###
GET http://localhost:3000/api/post/{{post1}}
Content-Type: {{ctype}}
Authorization: Bearer {{token}}


###
POST http://localhost:3000/api/post
Content-Type: {{ctype}}
Authorization: Bearer {{token}}

{
    "content": "POST BY USER NEWWW"
}

###
POST http://localhost:3000/api/post/{{post1}}
Content-Type: {{ctype}}
Authorization: Bearer {{token}}

{
    "content": "My edited contetn"
}


###
DELETE http://localhost:3000/api/post/{{post1}}
Content-Type: {{ctype}}
Authorization: Bearer {{token}}



###
GET http://localhost:3000/api/post/{{post1}}/comment
Content-Type: {{ctype}}
Authorization: Bearer {{token}}


###
POST http://localhost:3000/api/post/{{post1}}/comment
Content-Type: {{ctype}}
Authorization: Bearer {{token}}

{
    "content": "Road admin comment"
}

### 

// please chang comment id
@commentadmin = 5fafe7414f1cd32cec065816
@commentuser = 5fafbc3d21756b65f1d705be

###
POST http://localhost:3000/api/comment/{{commentadmin}}
Content-Type: {{ctype}}
Authorization: Bearer {{token}}

{
    "content": "ROAD EDTIED"
}


###
DELETE http://localhost:3000/api/comment/{{commentadmin}}
Content-Type: {{ctype}}
Authorization: Bearer {{token}}


###
