http://localhost:3000

###
http://localhost:3000/login

###
http://localhost:3000/dev/register


###
http://localhost:3000/user/:userId


###
http://localhost:3000/post


###
http://localhost:3000/post/:postId


###
http://localhost:3000/post


###
http://localhost:3000/post/:postId


###
http://localhost:3000/post/:postId


###
http://localhost:3000/post/:postId/comment


###
http://localhost:3000/post/:postId/comment


###
http://localhost:3000/comment/:commentId


###
http://localhost:3000/comment/:commentId


###
